version: 2.1 

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
        key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
  save_cache_cmd:
    steps:
      - save_cache:
        paths:
          - ~/.cache/yarn
        key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    docker:
      image: cimg/node:10.10.1

    steps:

      - checkout
      - restore_cache_cmd
      - run: yarn global add node-gyp && yarn install
      - save_cache_cmd






